### ISSUE TITLE
emojis are stretched

### ISSUE THREAD

**Issue by SimonEnsemble** [pro-panda/parchment#1]
hi. super awesome theme, thank you!
I thought this was [an issue ](https://github.com/jekyll/jemoji/issues/93?email_source=notifications&email_token=AHJZNNRBEOIFCRZKNJR7PRDP2XJLHA5CNFSM4HYPWSIKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXZF62I#issuecomment-502423401)with `jemoji`, but apparently there is a css line in your theme that makes emojis stretched. If I comment out the 100% width line, the image on my main page is too large. Is there a way I can make emojis work with your theme? Thanks.

```css
.content img {
  text-align: center;
  width: 100%;
}
```

**Comment by pro-panda** [comment]
Thanks for reporting. Will see this over the weekend

**Comment by rhl-bthr** [comment]
```
img {
    text-align: center;
    width: 100%;
}
```
Instead of generalizing the style for all images, you can replace it with,

```
.banner {
    text-align: center;
}
.jemomji {
    text-align: center;
    width: 100%;
}
```

While adding a jemoji, write like,
```
<img class = "jemoji"> ... </img>
```
While adding a banner, write like,
```
<img class = "banner"> ... </img>
```
