### ISSUE TITLE
Navigation bar offset

### ISSUE THREAD

**Issue by ghost** [pro-panda/parchment#26]
Hello,

As you can see between this [page](https://pro-panda.github.io/parchment/) and this [page](https://pro-panda.github.io/parchment/2018-10-20-markdown-posts/), the navigation bar moves when the article is larger.

How to fix this issue?

Thank you!

**Comment by tetri** [comment]
hello,

this is due to the browser scroll, isn't it?

**Comment by rhl-bthr** [comment]
@tetri, yes
