### ISSUE TITLE
Broken styles after 7 or more posts. 

### ISSUE THREAD

**Issue by maximousblk** [pro-panda/parchment#3]
[my site](../) (no more legible as an example for this issue)

When there are 7 or more posts on the blog the styles tend to break. The snippets are larger than the title, tags page is enlarged, etc.

***NOTE:*** I tested and built my version solely on my phone and is not tested on a desktop but it breaks when I open it in Chrome's desktop mode.

**Comment by maximousblk** [comment]
As a solution to this, I tried adding pagination and it seems to be working now.

**Comment by pro-panda** [comment]
Thanks for reporting. Will review by next week

**Comment by rhl-bthr** [comment]
I'm unable to reproduce the issue after following the steps you mentioned.
Could you please provide a screenshot of the behaviour?

**Comment by maximousblk** [comment]
I used my phone, but I think this can be a problem for vertical monitors too.

![Screenshot_20200203-113908_Chrome](https://user-images.githubusercontent.com/28438021/73629760-1de93a80-467a-11ea-8357-f50c705e865c.jpg)

As you can see, post snippets are a larger font than titles.
